#!/bin/bash
set -e

root=$(dirname $(readlink -f $0))

case $1 in
    setup);&
    s) sh $root/script/setup.sh;;
    clear);&
    c) sh $root/script/clear.sh;;
    install);&
    i) sh $root/script/install.sh;;
    generate);&
    g) sh $root/script/generate.sh;;
    build);&
    b) sh $root/script/build.sh;;
    test);&
    t) sh $root/script/test.sh;;
    run);&
    r) sh $root/script/run.sh $2;;
    help);& h);&
    *) echo "
Toy Compiler Project

Usage: sh ./start.sh [options] <path?>

Options:
    s   setup       Setup environment and install basic dependencies.
    c   clear       Clear parser and temporary files generated by tests and CMake.
    i   install     Use CMake to load project and create cache files.
    g   generate    Use Flex and Bison generate syntax parser sources.
    b   build       Build excutable file of CMake target.
    t   test        Test built binary and show its functions.   (Need to complete)
    r   run <path>  Run compiler with <path> input file. 
    h   help        Show this menu, any token will point to this page.
    
Created by Nanami 20/11/23, for academic use.
";;
esac

